### ISSUE TITLE
Subscription activity is not updated

### ISSUE THREAD

**Issue by baio** [Azure/ng-deploy-azure#87] opened 2019-11-29 09:13 UTC
When you first add deploy with inactive subscription you got 
You don't have any active subscriptions. Head to https://azure.com/free and sign in. From there you can create a new subscription and then you can come back and try again.

Then activate account (old one)

After this `ng add @azure/ng-deploy ` just stuck to 
`You don't have any active subscriptions. Head to https://azure.com/free and sign in. From there you can create a new subscription and then you can come back and try again.`

Though subscription already active.

Had to move to firebase (

**Comment by doggy8088** [comment] 2020-02-08 16:31
I have exact the same issue happened.  How can I debug this?

![image](https://user-images.githubusercontent.com/88981/74088635-6d44c600-4ad3-11ea-89e8-a3f277c3451d.png)

**Comment by doggy8088** [comment] 2020-02-08 16:58
I just found I need to delete `%LOCALAPPDATA%\@azure\ng-deploy-nodejs\Config\ng-azure.json` file to make logout successfully.

**Comment by manekinekko** [comment] 2020-02-09 01:25
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/Azure/ng-deploy-azure/issues/55. Please subscribe to that issue for future updates.

**Closed by manekinekko** 2020-02-09 01:25 UTC
